"""Add detailed financial fields to annual_reports table

Revision ID: 6a098c17b026
Revises:
Create Date: 2025-08-21 16:52:26.724359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a098c17b026'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('orgnummer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_orgnummer'), 'companies', ['orgnummer'], unique=True)
    op.create_table('annual_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('bs_materiella_anlaggningstillgangar', sa.Float(), nullable=True),
    sa.Column('bs_finansiella_anlaggningstillgangar', sa.Float(), nullable=True),
    sa.Column('bs_varulager', sa.Float(), nullable=True),
    sa.Column('bs_kundfordringar', sa.Float(), nullable=True),
    sa.Column('bs_ovriga_fordringar', sa.Float(), nullable=True),
    sa.Column('bs_forutbetalda_kostnader', sa.Float(), nullable=True),
    sa.Column('bs_kassa_bank', sa.Float(), nullable=True),
    sa.Column('bs_bundet_eget_kapital', sa.Float(), nullable=True),
    sa.Column('bs_fritt_eget_kapital', sa.Float(), nullable=True),
    sa.Column('bs_arets_resultat_ek', sa.Float(), nullable=True),
    sa.Column('bs_obeskattade_reserver', sa.Float(), nullable=True),
    sa.Column('bs_langfristiga_skulder', sa.Float(), nullable=True),
    sa.Column('bs_kortfristiga_skulder', sa.Float(), nullable=True),
    sa.Column('is_nettoomsattning', sa.Float(), nullable=True),
    sa.Column('is_forandring_lager', sa.Float(), nullable=True),
    sa.Column('is_ovriga_rorelseintakter', sa.Float(), nullable=True),
    sa.Column('is_kostnad_ravaror', sa.Float(), nullable=True),
    sa.Column('is_kostnad_externa', sa.Float(), nullable=True),
    sa.Column('is_kostnad_personal', sa.Float(), nullable=True),
    sa.Column('is_avskrivningar', sa.Float(), nullable=True),
    sa.Column('is_finansiella_intakter', sa.Float(), nullable=True),
    sa.Column('is_finansiella_kostnader', sa.Float(), nullable=True),
    sa.Column('is_bokslutsdispositioner', sa.Float(), nullable=True),
    sa.Column('is_skatt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_reports_id'), 'annual_reports', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['annual_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_annual_reports_id'), table_name='annual_reports')
    op.drop_table('annual_reports')
    op.drop_index(op.f('ix_companies_orgnummer'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
